- .gitignore
- Gemfile
- Gemfile.lock
- app/models/category.rb
- app/models/company.rb
- app/models/experience.rb
- app/models/notification.rb
- app/models/post.rb
- app/models/profile.rb
- app/models/skill.rb
- app/models/user.rb
- app/models/user_apply.rb
- app/models/view.rb
- db/migrate/20200602012402_create_skills.rb
- db/migrate/20200602012550_create_categories.rb
- db/migrate/20200602013729_create_users.rb
- db/migrate/20200602014407_create_posts.rb
- db/migrate/20200602014658_create_profiles.rb
- db/migrate/20200602014949_create_experiences.rb
- db/migrate/20200602015144_create_companies.rb
- db/migrate/20200602015336_create_notifications.rb
- db/migrate/20200602015917_create_user_applies.rb
- db/migrate/20200602032108_create_views.rb
- db/schema.rb
https://edu-redmine.sun-asterisk.vn/issues/24375
> Refs [task] [24375] Init model

- Gemfile
- Gemfile.lock
- app/controllers/sessions_controller.rb
- app/controllers/static_pages_controller.rb
- app/models/post.rb
- app/models/user.rb
- app/views/layouts/_header.html.erb
- app/views/posts/_post.html.erb
- app/views/shared/_feed.html.erb
- app/views/static_pages/home.html.erb
- config/locales/en.yml
- config/locales/vi.yml
- config/settings.yml
- db/migrate/20200604023645_change_column_name.rb
- db/migrate/20200605021256_add_index_post.rb
- db/schema.rb
- db/seeds.rb
https://edu-redmine.sun-asterisk.vn/issues/24286
> Refs [Task][24286] list all job

- app/controllers/admin/posts_controller.rb
- app/helpers/admin/posts_helper.rb
- app/models/post.rb
- app/models/profile.rb
- app/models/skill.rb
- app/views/admin/posts/_post_form.html.erb
- app/views/admin/posts/new.html.erb
- app/views/shared/_error_messages.html.erb
- config/locales/en.yml
- config/locales/vi.yml
- config/routes.rb
- config/settings.yml
- db/migrate/20200605092728_remove_skill_id_from_posts.rb
- db/migrate/20200605093727_remove_skill_id_from_profiles.rb
- db/migrate/20200608032930_add_skillable_type_and_skillable_id_to_skills.rb
- db/schema.rb
https://edu-redmine.sun-asterisk.vn/issues/24297
> Refs [Task][24297] Create job

- app/controllers/admin/posts_controller.rb
- app/controllers/application_controller.rb
- app/helpers/admin/posts_helper.rb
- app/javascript/packs/application.js
- app/javascript/packs/datatable.js
- app/models/post.rb
- app/views/admin/posts/_post.html.erb
- app/views/admin/posts/index.html.erb
- config/locales/en.yml
- config/locales/vi.yml
- config/routes.rb
- config/settings.yml
- config/webpack/environment.js
- package.json
- yarn.lock
https://edu-redmine.sun-asterisk.vn/issues/24299
> Refs [Task][24299] List all post, delete post

- app/controllers/admin/user_applies_controller.rb
- app/helpers/admin/user_applies_helper.rb
- app/javascript/packs/application.js
- app/models/user.rb
- app/models/user_apply.rb
- app/views/admin/user_applies/_user_apply.html.erb
- app/views/admin/user_applies/index.html.erb
- config/locales/en.yml
- config/locales/vi.yml
- config/routes.rb
https://edu-redmine.sun-asterisk.vn/issues/24300
> Refs [Task][24300] Approved user

- app/assets/stylesheets/custom.scss
- app/controllers/admin/companies_controller.rb
- app/helpers/admin/admins_helper.rb
- app/javascript/packs/application.js
- app/models/company.rb
- app/views/admin/companies/_company_form.html.erb
- app/views/admin/companies/edit.html.erb
- app/views/admin/companies/index.html.erb
- app/views/admin/posts/_post.html.erb
- app/views/admin/posts/_post_form.html.erb
- app/views/admin/posts/index.html.erb
- app/views/admin/posts/new.html.erb
- app/views/admin/profiles/show.html.erb
- app/views/admin/user_applies/_user_apply.html.erb
- app/views/admin/user_applies/index.html.erb
- app/views/layouts/_sidebar.html.erb
- app/views/layouts/admin.html.erb
- config/locales/en.yml
- config/locales/vi.yml
- config/routes.rb
- config/settings.yml
- package.json
- yarn.lock
https://edu-redmine.sun-asterisk.vn/issues/24296
> Refs [Task][24296] Update info company

- app/assets/stylesheets/custom.scss
- app/controllers/status_profiles_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- app/views/profiles/_profile.html.erb
- config/locales/en.yml
- config/locales/vi.yml
- config/routes.rb
https://edu-redmine.sun-asterisk.vn/issues/24292
> [Ref][Task] 24292 public private cv

- spec/models/post_spec.rb
https://edu-redmine.sun-asterisk.vn/issues/24941
> [Resf][Task][24941] Rspec model post

- app/javascript/packs/application.js
- app/javascript/packs/datatable.js
- app/models/post.rb
- app/views/admin/posts/_post_form.html.erb
- app/views/admin/posts/_skill_fields.html.erb
- config/locales/en.yml
- config/locales/vi.yml
https://edu-redmine.sun-asterisk.vn/issues/25071
> [Refs][Task][25071] remove skill

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/custom.scss
- app/controllers/admin/posts_controller.rb
- app/controllers/admin/profiles_controller.rb
- app/models/qualification.rb
- app/views/admin/posts/_search_post.html.erb
- app/views/admin/posts/index.html.erb
- app/views/admin/profiles/_qualification.html.erb
- app/views/admin/profiles/show.html.erb
- app/views/admin/user_applies/_user_apply.html.erb
- config/locales/en.yml
- config/locales/vi.yml
https://edu-redmine.sun-asterisk.vn/issues/25133
> [Refs][Task][25133] Add gem ransack

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/admin/admins_controller.rb
- app/controllers/application_controller.rb
- app/controllers/profiles_controller.rb
- app/controllers/user_applies_controller.rb
- app/javascript/packs/application.js
- app/javascript/packs/custom.js
- app/models/ability.rb
- app/views/layouts/_header.html.erb
- app/views/profiles/_profile.html.erb
- app/views/shared/_notice_messages.html.erb
- config/locales/en.yml
- config/locales/vi.yml
https://edu-redmine.sun-asterisk.vn/issues/25143
> [Refs][Task][25143] add gem cancancan

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/custom.scss
- app/controllers/admin/user_applies_controller.rb
- app/helpers/admin/user_applies_helper.rb
- app/jobs/send_email_job.rb
- app/mailers/application_mailer.rb
- app/mailers/user_apply_mailer.rb
- app/models/user_apply.rb
- app/views/admin/user_applies/_user_apply.html.erb
- app/views/user_apply_mailer/approved.html.erb
- app/views/user_apply_mailer/approved.text.erb
- app/views/user_apply_mailer/cancel.html.erb
- app/views/user_apply_mailer/cancel.text.erb
- config/application.rb
- config/environments/development.rb
- config/locales/en.yml
- config/locales/vi.yml
- config/routes.rb
https://edu-redmine.sun-asterisk.vn/issues/25411
> [Refs][Task] add gem sidekiq

- Gemfile
- Gemfile.lock
- app/models/company.rb
- app/models/experience.rb
- app/models/post.rb
- app/models/profile.rb
- app/models/profile_skill.rb
- app/models/qualification.rb
- app/models/user.rb
- app/views/users/show.html.erb
- db/migrate/20200724064658_add_deleted_at_to_profiles.rb
- db/migrate/20200724071230_add_deleted_at_to_posts.rb
- db/migrate/20200724071508_add_deleted_at_to_users.rb
- db/migrate/20200724071800_add_deleted_at_to_profile_skills.rb
- db/migrate/20200724071819_add_deleted_at_to_qualifications.rb
- db/migrate/20200724071921_add_deleted_at_to_experiences.rb
- db/migrate/20200724071943_add_deleted_at_to_companies.rb
- db/schema.rb
https://edu-redmine.sun-asterisk.vn/issues/25585?issue_count=27&issue_position=1&next_issue_id=25584
> [Ref] [Task] 25585 paronaia

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/custom.scss
- app/controllers/admin/admins_controller.rb
- app/helpers/application_helper.rb
- app/javascript/packs/application.js
- app/models/application_record.rb
- app/models/profile.rb
- app/views/admin/admins/_chart.html.erb
- app/views/admin/admins/_profile_applies_chart.html.erb
- app/views/admin/admins/index.html.erb
- app/views/admin/profiles/show.html.erb
- app/views/posts/show.html.erb
- config/locales/en.yml
- config/locales/vi.yml
- package.json
- yarn.lock
https://edu-redmine.sun-asterisk.vn/issues/24295
> [Ref] [task] 24295 chartkick

- app/channels/application_cable/connection.rb
- app/channels/notifications_channel.rb
- app/javascript/channels/notifications_channel.js
- app/jobs/notification_relay_job.rb
- app/models/notification.rb
- config/cable.yml
- config/routes.rb
https://edu-redmine.sun-asterisk.vn/issues/24294
> [Ref][Task] 24294 Realtime notificationv2

- app/assets/stylesheets/client.scss
- app/channels/application_cable/connection.rb
- app/controllers/job_applieds_controller.rb
- app/controllers/searches_controller.rb
- app/javascript/packs/regex_password.js
- app/models/notification.rb
- app/models/post.rb
- app/views/job_applieds/_job_applied.html.erb
- app/views/notifications/_notification.html.erb
- app/views/notifications/index.html.erb
- app/views/posts/_post.html.erb
- app/views/posts/_search.html.erb
- app/views/profiles/_profile.html.erb
- app/views/searches/index.html.erb
- app/views/shared/_feed.html.erb
- app/views/users/show.html.erb
- config/environments/development.rb
- config/locales/en.yml
- config/locales/vi.yml
- config/routes.rb
- config/settings.yml
- db/seeds.rb
https://edu-redmine.sun-asterisk.vn/issues/26874
> [Ref][Task] 26874 Find job

- app/assets/stylesheets/client.scss
- app/controllers/profiles_controller.rb
- app/controllers/searches_controller.rb
- app/helpers/application_helper.rb
- app/javascript/channels/notifications_channel.js
- app/jobs/notification_relay_job.rb
- app/models/notification.rb
- app/views/layouts/_header.html.erb
- app/views/posts/_search.html.erb
- app/views/searches/index.html.erb
- config/locales/en.yml
- config/locales/vi.yml
- config/settings.yml
- db/migrate/20200814064001_add_viewed_in_notification.rb
- db/schema.rb
- spec/controllers/notifications_controller_spec.rb
- spec/factories/company.rb
- spec/models/notification_spec.rb
- spec/support/spec_test_helper.rb
https://edu-redmine.sun-asterisk.vn/issues/27595
> [Ref][Task] 27595 improver v1

- app/assets/stylesheets/client.scss
- app/assets/stylesheets/colors.scss
- app/controllers/profiles_controller.rb
- app/helpers/admin/admins_helper.rb
- app/helpers/application_helper.rb
- app/javascript/packs/application.js
- app/javascript/packs/count_association.js
- app/models/profile.rb
- app/views/layouts/application.html.erb
- app/views/profiles/_experience_fields.html.erb
- app/views/profiles/_form.html.erb
- app/views/profiles/_profile_skill_fields.html.erb
- app/views/profiles/_qualification_fields.html.erb
- config/locales/en.yml
- config/locales/vi.yml
- config/settings.yml
https://edu-redmine.sun-asterisk.vn/issues/28145
> [Ref] [task] #28145 Improve 3

- app/assets/stylesheets/client.scss
- app/javascript/packs/application.js
- app/javascript/packs/enter_comment.js
- app/views/comments/_comment.html.erb
- app/views/comments/_form_comment.html.erb
- app/views/comments/edit.js.erb
- app/views/posts/show.html.erb
- config/locales/en.yml
- config/locales/vi.yml
https://edu-redmine.sun-asterisk.vn/issues/28950?issue_count=58
> [Ref] [task] #28950 improve 5

- Gemfile
- Gemfile.lock
- app/api/api.rb
- app/api/error_formatter.rb
- app/api/find_job/v1/posts.rb
- app/api/find_job/v1/root.rb
- app/api/find_job/v1/users.rb
- config/application.rb
- config/initializers/inflections.rb
- config/routes.rb
- db/seeds.rb
- lib/tasks/routes.rake
https://edu-redmine.sun-asterisk.vn/issues/29743
> [Ref][Task]#29743 Grape API
